{% set name = "lsst-efd-client" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lsst-efd-client-{{ version }}.tar.gz
  sha256: e304340eae2ca5fc390646278f2bb31679e799cabf0a3d2d0e778a8cdc36b141

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.6
    - pip ==19.2.3
    - bump2version ==0.5.11
    - wheel ==0.33.6
    - watchdog ==0.9.0
    - flake8 ==3.7.8
    - coverage ==4.5.4
    - twine
    - pytest-runner
  run:
    - python >=3.5
    - numpy >=1.16.5
    - aioinflux
    - pandas
    - astropy
    - pyyaml
    - pytables
    - kafkit
    - requests
    - legacy-cgi   # [py>=312]

test:
  imports:
    - lsst_efd_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lsst-sqre/lsst-efd-client
  summary: Utility classes for working with the LSST EFD.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ktlim
